# Learning [NumPy](https://numpy.org/)

In [50]:
print("Hello, idiots!")

Hello, idiots!


### Import package
import numpy with alias np

In [51]:
import numpy as np

## Arrays in NumPy

### Basic function
array([my array]): used to create an array

In [52]:
arr = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arr[1, 2]

3

### zeros()
zeros(size) creates a function with all 0

ones(size, dtype) #datatype

In [53]:
arr = np.zeros(5)
print(arr)

arr = np.zeros(5, dtype = np.int64)
print(arr)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


### ones()
ones(size) creates an array with all 1

ones(size, dtype) #datatype

In [54]:
arr = np.ones(5)
print(arr)

arr = np.ones(5, dtype = np.int64)
print(arr)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


### empty()
empty() creates a function with garbage values

In [55]:
arr = np.empty(2)
arr

array([2.00000000e+000, 6.92489598e-310])

### arange()
arange() creates an array with a range of elements.

arange(startNumber, lastNumber, stepSize)

In [56]:
arr = np.arange(9)
print(arr)
arr = np.arange(1, 15, 3)
print(arr)

[0 1 2 3 4 5 6 7 8]
[ 1  4  7 10 13]


### linespace()
linspace(start, stop, num = 50 #katka, endpoint = True, retstep = False, dtype = None)
               
creates an array with values spaced linearly in a specified interval

In [57]:
arr = np.linspace(0, 9, 100)
arr

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

## Adding, removing, and sorting elements

### sort()
you need a description!?!?!?

In [59]:
arr = np.array([6, 7, 4, 3, 5, 3, 6, 1, 2, 0])
np.sort(arr)

array([0, 1, 2, 3, 3, 4, 5, 6, 6, 7])